Create Blogging On Nostr
plebnet-dev/website pull request #74
Opened 2023-10-28 18:59 UTC by BrutusBondBTC

Added A blogpost.  I hosted the images on nostr.build. I'm not sure if I should upload them to github instead.

2023-10-29 19:09 UTC, bitkarrot commented
Blog looks awesome! @BrutusBondBTC 

BTW, you forgot the metadata and the post name should replace spaces with _ and end in ".md" 

Example Metadata from https://raw.githubusercontent.com/plebnet-dev/website/main/src/content/post/crafting_your_story.md
---
publishDate: 2023-10-07T20:22:00-05:00
title: Crafting Your Story - Paving Your Way to a Bitcoin Career
author: Brandon Sauceda
description: Learn how to share your unique journey into Bitcoin.
image: /images/bitcoin_community_growth.png
category: Education
tags:
  - Bitcoin
---

If you need some tag suggestions, @saucy-tech 

Since @bliotti is working on images on the other PR, I can merge this one in without and we'll add the images later.

2023-10-29 19:11 UTC, bitkarrot requested changes

2023-10-29 19:11 UTC, bitkarrot commented on src/content/post/Blogging On Nostr
> +
Add metadata to the top of the blog post here.

2023-10-29 20:26 UTC, saucy-tech requested changes
This is great. Yes please include the frontmatter. I'd recommend the Opinion category and a nostr tag.

```
---
publishDate: 2023-10-07T20:22:00-05:00
title: Your Blog Post Title
author: Your Name
description: Short description on blog
image: /images/your_image_here.png
categories:
  - Opinion
tags:
  - nostr
---
```

2023-10-31 01:59 UTC, BrutusBondBTC commented
Thanks. I didn't even know about tags, metadata or frontmatter.

2023-11-01 02:04 UTC, bitkarrot commented
> Thanks. I didn't even know about tags, metadata or frontmatter.

No worries, This branch will need to be updated, please see comment from https://github.com/plebnet-dev/website/pull/72#issuecomment-1788282520

2023-11-03 01:14 UTC, BrutusBondBTC reviewed
I redid the post, added the metadata and changed a few typos, but now I'm not sure how to submit it again.

2023-11-03 01:15 UTC, bitkarrot commented
@BrutusBondBTC how about, close this PR and make a new one? might be easier for you.

2023-11-07 17:43 UTC, bitkarrot commented
bump. @BrutusBondBTC

2023-11-07 19:46 UTC, bitkarrot commented
OK I see the metadata, please also edit the file name on your branch so that it has no spaces and ends with .md , Example "Blogging_on_Nostr.md"

@amsalmeron invited you as reviewer, please help confirm that the blog post displays correctly.


<img width="786" alt="Screenshot 2023-11-07 at 11 44 02 AM" src="https://github.com/plebnet-dev/website/assets/73979971/97433a91-6e1b-405b-ac24-29fe641035bb">

2023-11-07 19:51 UTC, bitkarrot commented
@BrutusBondBTC you can 1-click edit on github web

<img width="1129" alt="Screenshot 2023-11-07 at 11 50 11 AM" src="https://github.com/plebnet-dev/website/assets/73979971/e232e24a-9695-4ac9-b310-f08071fa184d">

2023-11-07 23:11 UTC, BrutusBondBTC commented
Ok. I’ll try this when I get home from the grocery store.

2023-11-08 20:23 UTC, BrutusBondBTC commented
I think I did this. Did it work?

2023-11-08 20:54 UTC, bitkarrot commented
> I think I did this. Did it work?

It still has the old name without the "_'' and the .md ending on this branch.

2023-11-10 19:00 UTC, bitkarrot commented
I updated it for you, and will merge in a bit

2023-11-10 19:00 UTC, bitkarrot approved these changes

2023-11-10 19:00 UTC, merged