October blog meeting minutes
plebnet-dev/website pull request #80
Opened 2023-11-02 01:58 UTC by surfersol

2023-11-02 02:33 UTC, bitkarrot commented
@saucy-tech please to review tags. 

@bliotti  Good idea to add the meeting minutes to the website, I don't know why we didn't do it before, as there is a repo here..... https://github.com/plebnet-dev/meeting-notes

Either we consolidate everything into the website or add a copy for October Meeting to the meeting-notes repo as well for easy reference, as the entire history is currently over there. Opinions on organizing this welcome, especially on tags, @saucy-tech, @surfersol @bliotti

2023-11-02 02:35 UTC, bitkarrot requested changes
review made, please see requested changes @surfersol . Thanks!

2023-11-02 02:35 UTC, bitkarrot commented on src/content/post/surfersol_blogpost.md
> +| [Resources](https://metadata.plebnet.dev/)
Update [Resources] to [Backup your Nostr Metadata]

2023-11-02 02:35 UTC, bitkarrot commented on src/content/post/surfersol_blogpost.md
> +  - lightning-network
@saucy-tech please comment on tags

2023-11-02 02:35 UTC, bitkarrot commented on src/content/post/surfersol_blogpost.md
> +- [Completion of a LNBITS or GetAlby Pull Request would gets a free 2024 Bitcoin Tix Open Source](https://b.tc/conference/opensource)
Not sure if getAlby is on the list. I think its only LNBits but please cross check. thanks

2023-11-02 16:41 UTC, saucy-tech requested changes

2023-11-02 16:41 UTC, saucy-tech commented on src/content/post/surfersol_blogpost.md
> +  - lightning-network
I'd recommend to use 
```
category: News and Updates
tags:
 - events
 - monthly meetup
```

2023-11-02 17:12 UTC, saucy-tech commented
@bitkarrot @bliotti @surfersol my thoughts on this is I'd prefer to keep meeting minutes in the github repo but include a repo link in our events blog post. We could add a sentence to the discord event monthly meetup saying "Checkout previous monthly meetup meetings here <url>.". This would then carryover when we get the python github actions setup (I'm working on it this weekend). 

We could spruce up the meeting minutes template if you wanted, and should reuse it month to month for consistency.

2023-11-02 17:28 UTC, bitkarrot commented
> @bitkarrot @bliotti @surfersol my thoughts on this is I'd prefer to keep meeting minutes in the github repo but include a repo link in our events blog post. We could add a sentence to the discord event monthly meetup saying "Checkout previous monthly meetup meetings here .". This would then carryover when we get the python github actions setup (I'm working on it this weekend).
> 

That's a fantastic idea. I'm giving @saucy-tech idea a thumbs up. This way we have everything in one place. The event page is a good place to link to the git repo for meeting minutes. here's the location for the october meetup: https://github.com/plebnet-dev/website/blob/main/src/content/post/events.md#event-october-monthly-meetup

> We could spruce up the meeting minutes template if you wanted, and should reuse it month to month for consistency.

Sure!  Anybody want to create a template? @surfersol , @surfersol ? Definitely could use a meeting template, a good place to add it would be the meeting-notes repo. Also see the old meeting minutes as a point of reference: https://github.com/plebnet-dev/meeting-notes

2023-11-02 17:32 UTC, bitkarrot commented on src/content/post/surfersol_blogpost.md
> +  - lightning-network
@surfersol

2023-11-02 18:02 UTC, bitkarrot commented
@surfersol I'd recommend making the Monthly Plebnet member contributions (the PRs) a separate blog post. Just keep the meeting-notes in the meeting repository.

2023-11-03 00:25 UTC, surfersol commented
Modifying / moving the meeting minutes to https://github.com/plebnet-dev/meeting-notes

2023-11-03 00:25 UTC, closed without merging